
import styles from './EssayScoreCard.module.css';

interface Props {
  score: number;
  maxScore: number;
  percentage: number;
  ratingBand: string;
}

export default function EssayScoreCard({ score, maxScore, percentage, ratingBand }: Props) {
  
  const getBandColor = () => {
    switch(ratingBand) {
      case 'excellent': return '#10b981'; // Green
      case 'good': return '#3b82f6'; // Blue
      case 'average': return '#f59e0b'; // Amber
      case 'weak': return '#f97316'; // Orange
      case 'poor': return '#ef4444'; // Red
      default: return '#6b7280';
    }
  };

  return (
    <div className={styles.card}>
      <h3 className={styles.title}>AI Evaluation Score</h3>
      <div className={styles.scoreCircleWrapper}>
        <div 
          className={styles.scoreCircle} 
          style={{ borderColor: getBandColor() }}
        >
          <span className={styles.scoreValue}>{score}</span>
          <span className={styles.scoreMax}>/ {maxScore}</span>
        </div>
      </div>
      <div className={styles.metaInfo}>
        <div className={styles.bandBadge} style={{ backgroundColor: getBandColor() }}>
          {ratingBand.toUpperCase()}
        </div>
        <div className={styles.percentageText}>{percentage.toFixed(1)}%</div>
      </div>
      <p className={styles.disclaimer}>
        * This score is advisory and generated by AI for practice purposes. It does not represent an official UPSC evaluation.
      </p>
    </div>
  );
}
