# Generated by Django 5.2.15 on 2026-06-17 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam', models.CharField(max_length=100)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('subtopic', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_type', models.CharField(max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('ingestion_date', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('document_hash', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
