# Generated by Django 5.2.15 on 2026-06-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTrack',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('gradient', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExamStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('stage_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowchart', to='exams.examtrack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(max_length=200)),
                ('details', models.JSONField(default=list, help_text='List of bullet points')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='exams.examtrack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
