# Generated by Django 5.2.15 on 2026-06-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_description', models.TextField()),
                ('documents_required', models.JSONField(default=list, help_text='List of required documents')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='exams.examtrack')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit', models.CharField(max_length=200)),
                ('educational_qualification', models.TextField()),
                ('nationality', models.CharField(max_length=200)),
                ('other_details', models.JSONField(default=dict, help_text='Dictionary for extra notes like physical standards')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='exams.examtrack')),
            ],
        ),
    ]
