# Generated by Django 5.2.15 on 2026-06-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_documentverification_eligibilitycriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoffTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_exam_name', models.CharField(help_text='e.g., SSC CGL, SSC CHSL, CDS IMA', max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('category', models.CharField(default='General (UR)', max_length=100)),
                ('stages', models.JSONField(default=dict, help_text="JSON representation of stages and marks, e.g. {'Prelims': 88.22, 'Mains': 748}")),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='exams.examtrack')),
            ],
            options={
                'ordering': ['sub_exam_name', '-year'],
            },
        ),
    ]
