# Generated by Django 5.2.15 on 2026-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_cutofftrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverification',
            name='category_verification',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific verification document list overrides'),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='category_eligibility',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific eligibility detail overrides'),
        ),
    ]
