# Generated by Django 5.2.15 on 2026-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_documentverification_category_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabussection',
            name='highest_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabussection',
            name='highest_marks_info',
            field=models.CharField(blank=True, help_text='Details about the highest scorer, year etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='syllabussection',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
