# Generated by Django 5.2.15 on 2026-06-16 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_quiz_quizquestion_quizregistration_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('date', 'track')},
        ),
    ]
