# Generated by Django 5.2.15 on 2026-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_quiz_date_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
