# Generated by Django 5.2.15 on 2026-06-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_quizsubmission_time_taken_seconds_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='marks_per_question',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_marking',
            field=models.FloatField(default=0.66),
        ),
        migrations.AddField(
            model_name='quiz',
            name='stage_name',
            field=models.CharField(default='Prelims', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('date', 'track', 'stage_name')},
        ),
        migrations.CreateModel(
            name='ExamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200)),
                ('total_questions', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('marks_per_question', models.FloatField()),
                ('negative_marking', models.FloatField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('last_verified', models.DateField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='exams.examtrack')),
            ],
        ),
    ]
