# Generated by Django 5.2.15 on 2026-06-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_quiz_unique_together_quiz_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
