# Generated by Django 5.2.15 on 2026-06-18 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnswerTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_text', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('detected_language', models.CharField(default='en', max_length=50)),
                ('extraction_quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='essay.essayquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='essay.essaypracticesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_transcripts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EssayAIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_score', models.IntegerField(default=125)),
                ('percentage', models.FloatField(default=0.0)),
                ('rating_band', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('weak', 'Weak'), ('poor', 'Poor')], default='average', max_length=20)),
                ('review_json', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('retrieved_context', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(default='mock_evaluator_v1', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='essay.essayquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='essay.essaypracticesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_essay_reviews', to=settings.AUTH_USER_MODEL)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='essay.essayanswertranscript')),
            ],
        ),
        migrations.CreateModel(
            name='EssayOCRPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('image_quality_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_page', to='essay.essayanswerimage')),
            ],
        ),
    ]
