# Generated by Django 5.2.15 on 2026-06-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
