# Generated by Django 5.2.15 on 2026-06-20 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_thread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='accepted_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_thread', to='threads.answer'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='thread',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
